# file salah: 100.mp3

# Senin
[[senin]]
jam = '16:43'
file = '1.mp3'

[[senin]]
jam = '16:44'
file = '2.mp3'

[[senin]]
jam = '16:45'
file = '3.mp3'

# Selasa
[[selasa]]
jam = '07:00'
file = '100.mp3'

# Rabu
[[rabu]]
jam = '07:00'
file = '1.mp3'

# Kamis
[[kamis]]
jam = '07:00'
file = '100.mp3'

# Jum'at (apostrop dihilangkan)
[[jumat]]
jam = '07:00'
file = '1.mp3'

# Sabtu
[[sabtu]]
jam = '07:00'
file = '1.mp3'
